name: Run tests on PR
# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Run tests
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm install
      - name: Run all tests
        run: npm test
